import { Inter } from "next/font/google";
import Providers from "./lib/Providers";
import { LayoutPublic } from "./layouts/index.style";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-Hant-TW">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Providers>
          <LayoutPublic>{children}</LayoutPublic>
        </Providers>
      </body>
    </html>
  );
}
